### PR TITLE
Allow nested monad return

### PR DESCRIPTION
**Pull request by jechol**
Make `return` in monad to be desugarized according to sample of inner-most monad.

### CODE REVIEW

**Comment by jechol** [comment]
@icidasset Could you review this?

**Review by expede — APPROVED** [review]
Well _hello again_ @jechol 👋 

Yeah, this totally makes sense. Thanks for catching that special case 😁 



P.S. Thanks for all the PRs, and apologies _again_ for the delays from the existing maintenance team. We're both actually at the same, super intense startup, so pretty much all other projects have been falling by the wayside.

We are looking for more maintainers; you're _already_ doing a great job. Please let me know if you'd be interested having higher rights to this repo.

**Comment by jechol** [comment]
> Well _hello again_ @jechol 👋
> 
> Yeah, this totally makes sense. Thanks for catching that special case 😁
> 
> 
> 
> P.S. Thanks for all the PRs, and apologies _again_ for the delays from the existing maintenance team. We're both actually at the same, super intense startup, so pretty much all other projects have been falling by the wayside.
> 
> We are looking for more maintainers; you're _already_ doing a great job. Please let me know if you'd be interested having higher rights to this repo.

I'm interested in having higher rights. Wanna contribute more.

**Comment by expede** [comment]
@Trevoke this has been sitting in my backlog _forever_ now — invite with higher rights sent!

**Comment by Trevoke** [comment]
@expede I believe you meant to ping @trevorite :D

**Comment by expede** [comment]
@Trevoke haha indeed! Apologies; I was fooled by GH autocomplete

**Comment by trevorite** [comment]
@expede I can't find the invitation. Could you please re-invite me? (I've changed my Github id from jechol to trevorite)

**Comment by expede** [comment]
Sent!

**Comment by trevorite** [comment]
It appears to be expired. Could you re-invite me?

CleanShot 2021-09-01 at 10 25 58

**Pull request merged**
